repo_token: BrWvblKgHEESffFZFS5qDVnHTPO0dzYUG

service_name: travis-pro
parallel: true

language: python
python:
  - 2.7
before_script:
  - git clone https://github.com/wtelecom/net-interviewer
  - cd net-interviewer
  - pip install -r requirements.txt
  - pip install coveralls
  - export PYTHONPATH=$PYTHONPATH:$PWD
script:
  - coverage run --source=interviewer test/runTests.py
after_success:
  - coverage report -m