repo_token: BrWvblKgHEESffFZFS5qDVnHTPO0dzYUG

service_name: travis-pro
parallel: true

language: python
python:
  - 2.7
  - 3.3
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=interviewer test/runTests.py test
after_success:
  - coveralls